# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-18 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xyz_util.modelutils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='\u59d3\u540d')),
                ('roles', xyz_util.modelutils.JSONField(blank=True, default={}, verbose_name='\u89d2\u8272')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='xauth_authority', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6743\u529b',
                'verbose_name_plural': '\u6743\u529b',
            },
        ),
    ]
